version: '3'

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        ports:
             - "2181:2181"
             - "2888:2888" 
             - "3888:3888"
        tty: false
        stdin_open: false

    kafka0:
        image: effeerre/kafka
        container_name: kafka0
        depends_on:
            - zookeeper
        links:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            - BROKER_ID=0
        stdin_open: true 
        tty: true

    kafka1:
        image: effeerre/kafka
        container_name: kafka1
        depends_on:
            - zookeeper
        links:
            - zookeeper
        ports:
            - "9093:9092"
        environment:
            - BROKER_ID=1
        stdin_open: true 
        tty: true

    kafka2:
        image: effeerre/kafka
        container_name: kafka2
        depends_on:
            - zookeeper
        links:
            - zookeeper
        ports:
            - "9094:9092"
        environment:
            - BROKER_ID=2
        stdin_open: true 
        tty: true
